create database customer_behavior;
use customer_behavior;
show tables;
select * from customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id ,purchase_amount
from customer
where discount_applied='YES' and purchase_amount>=(select avg(purchase_amount) from customer);
-- Q3. Which are the top 5 products with the highest average rating?
select distinct item_purchased,avg(review_rating) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status,count(customer_id) as total_customers ,
avg(purchase_amount) as avg_purchase,sum(purchase_amount)  as revenue
from customer
group by subscription_status 
order by revenue and avg_purchase;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select distinct item_purchased,
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end) /count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select * from customer;
with customer_type as (
select customer_id,previous_purchases,
CASE
WHEN previous_purchases =1 Then 'New'
When previous_purchases Between  2 and 10 Then "Returning"
Else 'Loyal'
End as customer_segment 
from customer
)
select customer_segment , count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH mostpurchase AS (
    SELECT  
        item_purchased,
        category, 
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    item_purchased, 
    category,
    total_orders 
FROM mostpurchase
WHERE item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status ;
-- Q10. What is the revenue contribution of each age group?
select age_group ,sum(purchase_amount) as total_revenue 
from customer
group by age_group 
order by total_revenue desc;

